import { Logo } from '@/components/LogosMarquee/LogosMarquee'

export const logos: Logo[] = [
	{
		id: 'metraflex',
		src: '/brands/metraflex.png',
		alt: 'metraflex',
		width: 160,
		height: 51,
	},
	{
		id: 'marathon',
		src: '/brands/marathon.png',
		alt: 'marathon',
		width: 160,
		height: 80,
	},
	{
		id: 'superior_tank',
		src: '/brands/superior_tank.png',
		alt: 'superior_tank',
		width: 160,
		height: 80,
	},
	{
		id: 'amtrol',
		src: '/brands/amtrol.png',
		alt: 'amtrol',
		width: 160,
		height: 80,
	},
	{
		id: 'bell_gosset',
		src: '/brands/bell_gosset.png',
		alt: 'bell_gosset',
		width: 160,
		height: 34,
	},
	{
		id: 'goulds',
		src: '/brands/goulds.png',
		alt: 'goulds',
		width: 160,
		height: 45,
	},
	{
		id: 'titus',
		src: '/brands/titus.png',
		alt: 'titus',
		width: 160,
		height: 58,
	},
	{
		id: 'big_ass_fans',
		src: '/brands/big_ass_fans.png',
		alt: 'big_ass_fans',
		width: 160,
		height: 53,
	},
	{
		id: 'flygt',
		src: '/brands/flygt.png',
		alt: 'flygt',
		width: 160,
		height: 53,
	},
	{
		id: 'ruskin',
		src: '/brands/ruskin.png',
		alt: 'ruskin',
		width: 160,
		height: 39,
	},
	{
		id: 'belimo',
		src: '/brands/belimo.png',
		alt: 'belimo',
		width: 160,
		height: 62,
	},
	{
		id: 'watts',
		src: '/brands/watts.png',
		alt: 'watts',
		width: 160,
		height: 40,
	},
	{
		id: 'sje',
		src: '/brands/sje.png',
		alt: 'sje',
		width: 160,
		height: 71,
	},
]
