import { Logo } from '@/components/LogosMarquee/LogosMarquee'

export const logos: Logo[] = [
	{
		id: 'metraflex',
		src: '/brands/metraflex.png',
		alt: 'metraflex',
		width: 160,
		height: 51,
		name: 'METRAFLEX',
	},
	{
		id: 'marathon',
		src: '/brands/marathon.png',
		alt: 'marathon',
		width: 160,
		height: 80,
		name: 'MARATHON',
	},
	{
		id: 'superior_tank',
		src: '/brands/superior_tank.png',
		alt: 'superior_tank',
		width: 160,
		height: 80,
		name: 'SUPERIOR TANK',
	},
	{
		id: 'amtrol',
		src: '/brands/amtrol.png',
		alt: 'amtrol',
		width: 160,
		height: 80,
		name: 'AMTROL',
	},
	{
		id: 'bell_gosset',
		src: '/brands/bell_gosset.png',
		alt: 'bell_gosset',
		width: 160,
		height: 34,
		name: 'BELL & GOSSETT',
	},
	{
		id: 'goulds',
		src: '/brands/goulds.png',
		alt: 'goulds',
		width: 160,
		height: 45,
		name: 'GOULDS',
	},
	{
		id: 'titus',
		src: '/brands/titus.png',
		alt: 'titus',
		width: 160,
		height: 58,
		name: 'TITUS',
	},
	{
		id: 'big_ass_fans',
		src: '/brands/big_ass_fans.png',
		alt: 'big_ass_fans',
		width: 160,
		height: 53,
		name: 'BIG ASS FANS COMPANY',
	},
	{
		id: 'flygt',
		src: '/brands/flygt.png',
		alt: 'flygt',
		width: 160,
		height: 53,
		name: 'FLYGT',
	},
	{
		id: 'ruskin',
		src: '/brands/ruskin.png',
		alt: 'ruskin',
		width: 160,
		height: 39,
		name: 'RUSKIN',
	},
	{
		id: 'belimo',
		src: '/brands/belimo.png',
		alt: 'belimo',
		width: 160,
		height: 62,
		name: 'BELIMO',
	},
	{
		id: 'watts',
		src: '/brands/watts.png',
		alt: 'watts',
		width: 160,
		height: 40,
		name: 'WATTS',
	},
	{
		id: 'sje',
		src: '/brands/sje.png',
		alt: 'sje',
		width: 160,
		height: 71,
		name: 'SJE',
	},
]
